### PR TITLE
"Priority System"

### PR DESCRIPTION
**Pull request by EOT3000**
Detects if server has vault. If it does, when a player bans another player, the plugin will check the metadata of both player's primary groups. If the ban sender's primary group's meta value "mcbansPriority" is larger than the victim of the ban primary group's "mcbansPriority", and the ban sender has the right permission, the ban succeeds, if not, then it doesn't. The new thread stuff is because my permissions plugin was complaining about "lookups on the main thread", so that shouldn't be changed

### CODE REVIEW

**Comment by EOT3000** [comment]
Also, don't set mcbans.ban.exempt. That will break everything

**Comment by EOT3000** [comment]
It compiles!

**Comment by EOT3000** [comment]
Don't use exempt permissions. That breaks it.

**Comment by firestar** [comment]
Thank you for the pull request.

**Pull request merged**
