### PR TITLE
BungeeCord Fix

### PR DESCRIPTION
**Pull request by rmarmorstein**
This is a small set of fixes for BungeeCord servers. It adds a small config section boolean for bungeecord, and if enabled, it will kick players when they are banned or kicked off of the proxy, not just their current server. This fixes http://goo.gl/Eu3mxk.

I've also made a small tweak to the gitignore to add some more things (used gitignore.io) and updated the maven pom.xml to use Spigot 1.8 and the new SpigotMC repository.

### CODE REVIEW

**Comment by Searchndstroy** [comment]
Why is the ByteArrayDataOutput a field? Would it not store data we don't need? (And cause some bugs/memory leaks?)

**Comment by Rmarmorstein** [comment]
See the latest commit, fixed that.

**Comment by Corpdraco** [comment]
Will test and update if so. Thank you!

**Comment by Rmarmorstein** [comment]
@Corpdraco this is over 2 years old and probably no longer relevant/applicable.

**Comment by Corpdraco** [comment]
@Rmarmorstein Will check the API docs and check for errors/usage before pushing it out. MCBans is long overdue for actual Bungeecord support.

**Comment by rmarmorstein** [comment]
This is 7 years old and obviously not getting merged.

**Pull request closed without merging**
